- name: Run edxapp migrations
  hosts: all
  sudo: False
  gather_facts: False
  tasks:
    - name: syncdb and migrate
      shell: >
        chdir={{ edxapp_code_dir }}
        python manage.py {{ item }} syncdb --migrate --settings=aws_migrate
      environment:
        DB_MIGRATION_USER: "{{ COMMON_MYSQL_MIGRATE_USER }}"
        DB_MIGRATION_PASS: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
      with_items:
        - lms
        - cms
