---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# based on instructions at https://github.com/mozilla/openbadges-badgekit/wiki/BadgeKit-Self-Hosting-Guide

- name: install nodejs - add ppa:chris-lea/node.js
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: install nodejs - ensure python-software-properties is installed
  apt: name=python-software-properties state=present

- name: install nodejs
  apt: name=nodejs update_cache=yes

- name: checkout badgekit-api repo
  git: >
    dest="{{ openbadges_code_dir }}/badgekit-api"
    repo='https://github.com/mozilla/badgekit-api.git'

- name: checkout openbadges-badgekit repo
  git: >
    dest="{{ openbadges_code_dir }}/openbadgekit-badgekit"
    repo='https://github.com/mozilla/openbadges-badgekit.git'

- name: install badgekit-api
  npm: path="{{ openbadges_code_dir }}/badgekit-api"

- name: setup badgekit api database
  mysql_db: name={{ openbadges_mysql_db }} state=present

- name: import badgekit default schema
  mysql_db: name={{ openbadges_mysql_db }} state=import target="{{ openbadges_code_dir }}/badgekit-api/schema.sql"

#- name: configure api

#- name: run badgekit api

#- name: configure badgekit

#- name: install badgekit dependencies

#- name: setup badgekit database

#- name: run badgekit
