---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role alton
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: install nodejs
    apt_repository: repo='ppa:chris-lea/node.js'
    apt: name=python-software-properties state=present
    apt: name=nodejs update_cache=yes

- name: clone api repo
    git: >
      dest={{ openbadges_code_dir }} repo='https://github.com/mozilla/badgekit-api.git'
      dest={{ openbadges_code_dir }} repo='https://github.com/mozilla/openbadges-badgekit.git'

- name: install api pre requisites
    npm: path="{{ openbadges_code_dir }}/badgekit-api"

- name: setup badgekit api database
    mysql_db: name={{ openbadges_mysql_db }} state=present
    mysql_db: name={{ openbadges_mysql_db }} state=import target="{{ openbadges_code_dir }}/badgekit-api/schema.sql"

- name: configure api

- name: run badgekit api

- name: configure badgekit

- name: install badgekit dependencies

- name: setup badgekit database

- name: run badgekit
