---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# based on instructions at https://github.com/mozilla/openbadges-badgekit/wiki/BadgeKit-Self-Hosting-Guide

- name: add ppa:chris-lea/node.js
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: install apt packages
  apt: pkg={{ item }}
  with_items:
  - mysql-server
  - python-software-properties
  - libmysqlclient-dev

- name: pip install mysql-python
  pip: name=mysql-python

- name: install nodejs
  apt: name=nodejs update_cache=yes

- name: checkout badgekit-api repo
  git: >
    dest="{{ openbadges_code_dir }}/badgekit-api"
    repo='https://github.com/mozilla/badgekit-api.git'

- name: checkout openbadges-badgekit repo
  git: >
    dest="{{ openbadges_code_dir }}/openbadgekit-badgekit"
    repo='https://github.com/mozilla/openbadges-badgekit.git'

- name: install npm foreman
  npm: name=foreman global=yes

- name: install badgekit-api
  npm: path="{{ openbadges_code_dir }}/badgekit-api"

- name: create badgekit api database
  mysql_db: name={{ api_mysql_db }} state=present

- name: import badgekit default schema
  mysql_db: >
    name={{ api_mysql_db }} state=import
    target="{{ openbadges_code_dir }}/badgekit-api/schema.sql"

- name: copy badgekit init system
  template: src=tmp/badgekit.sql.j2 dest=/tmp/badgekit.sql

- name: create badgekit system
  mysql_db: >
    name={{ api_mysql_db }} state=import
    target="/tmp/badgekit.sql"

- name: configure badgekit api
  template: >
    src=edx/app/openbadges/badgekit-api/.env.j2
    dest="{{ openbadges_code_dir }}/badgekit-api/.env"

- name: configure badgekit
  template: >
    src=edx/app/openbadges/openbadgekit-badgekit/config.json.j2
    dest="{{ openbadges_code_dir}}/openbadgekit-badgekit/config.json"

- name: install badgekit npm dependencies
  npm: path="{{ openbadges_code_dir }}/openbadgekit-badgekit"

- name: setup badgekit database
  mysql_db: name={{ badgekit_mysql_db }} state=present

- name: database migration
  command: bin/db-migrate up chdir="{{ openbadges_code_dir }}/openbadgekit-badgekit"

#- name: run badgekit api
#  command: nf start & chdir="{{ openbadges_code_dir }}/badgekit-api"

#- name: run badgekit
#  command: nf start & chdir="{{ openbadges_code_dir }}/openbadgekit-badgekit"
